version: "3.3"
services:
  web:
    build: .
    ports:
      - 80:80
      - 443:443
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data:rw
volumes:
  db:
